[package]
name = "otexplorer"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
publish = false


[dependencies]
xflags = "0.3.0"
read-fonts = { path = "../read-fonts",version = "0.19.1" }
font-types = { path = "../font-types",version = "0.5.4" }
ansi_term = "0.12.1"
atty = "0.2"

# cargo-release settings
[package.metadata.release]
release = false
