[package]
name = "font-test-data"
version = "1.0.0"
description = "Test data for the fontations crates"
readme = "README.md"

edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
read-fonts = { workspace = true }
write-fonts = { workspace = true }

