[workspace]

members = [
    "read-fonts",
    "font-types",
    "font-codegen",
    "font-test-data",
    "write-fonts",
    "otexplorer",
    "skrifa",
]

[workspace.dependencies]
# dev dependencies
pretty_assertions = "1.3.0"

[workspace.metadata.release]
allow-branch = ["main"]
