[package]
name = "kunnasta"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Library of constants related to font processing."
readme = "README.md"
categories = ["text-processing"]

[dependencies]
num_enum = "0.7"