# This is a 'codegen plan': it describes a series of steps to perform
# in order to regenerate all of this project's generated code.

# a list of directories that will be cleaned
clean = ["read-fonts/generated", "write-fonts/generated"]

# TODO: support a 'copy' step

# a mapping of files to generate, and their sources

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/colr.rs"
target = "read-fonts/generated/generated_colr.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cpal.rs"
target = "read-fonts/generated/generated_cpal.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/cpal.rs"
target = "write-fonts/generated/generated_cpal.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/font.rs"
target = "read-fonts/generated/font.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/font.rs"
target = "write-fonts/generated/generated_font.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/layout.rs"
target = "read-fonts/generated/generated_layout.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/layout.rs"
target = "write-fonts/generated/generated_layout.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gpos.rs"
target = "read-fonts/generated/generated_gpos.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gpos.rs"
target = "write-fonts/generated/generated_gpos.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gsub.rs"
target = "read-fonts/generated/generated_gsub.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gsub.rs"
target = "write-fonts/generated/generated_gsub.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cmap.rs"
target = "read-fonts/generated/generated_cmap.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/head.rs"
target = "read-fonts/generated/generated_head.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/head.rs"
target = "write-fonts/generated/generated_head.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/name.rs"
target = "read-fonts/generated/generated_name.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/name.rs"
target = "write-fonts/generated/generated_name.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/post.rs"
target = "read-fonts/generated/generated_post.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/post.rs"
target = "write-fonts/generated/generated_post.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/hhea.rs"
target = "read-fonts/generated/generated_hhea.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/hhea.rs"
target = "write-fonts/generated/generated_hhea.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/hmtx.rs"
target = "read-fonts/generated/generated_hmtx.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/hmtx.rs"
target = "write-fonts/generated/generated_hmtx.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/maxp.rs"
target = "read-fonts/generated/generated_maxp.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/maxp.rs"
target = "write-fonts/generated/generated_maxp.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/stat.rs"
target = "read-fonts/generated/generated_stat.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/glyf.rs"
target = "read-fonts/generated/generated_glyf.rs"

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/gdef.rs"
target = "read-fonts/generated/generated_gdef.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/gdef.rs"
target = "write-fonts/generated/generated_gdef.rs"

# modules just used for testing
[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test.rs"
target = "read-fonts/generated/generated_test.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test.rs"
target = "write-fonts/generated/generated_test.rs"

