# This is a 'codegen plan': it describes a series of steps to perform
# in order to regenerate all of this project's generated code.

# a list of directories that will be cleaned
clean = []

# modules just used for testing

[[generate]]
mode = "parse"
source = "resources/codegen_inputs/test.rs"
target = "read-fonts/generated/generated_test.rs"

[[generate]]
mode = "compile"
source = "resources/codegen_inputs/test.rs"
target = "write-fonts/generated/generated_test.rs"

