[package]
name = "klippa"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Subsetting a font file according to provided input."
repository = "https://github.com/googlefonts/fontations"
readme = "README.md"
categories = ["text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
thiserror = "1.0.58"
write-fonts = { path = "../write-fonts", features = ["read"] }
