[package]
name = "write-fonts"
version = "0.0.0"
edition = "2021"
license = "MIT/Apache-2.0"


[features]
parsing = ["read-fonts"]
default = ["parsing"]

[dependencies]
font-types = { path = "../font-types" }
read-fonts = { path = "../read-fonts", optional = true }
bitflags = "1.3"

[dev-dependencies]
diff = "0.1.12"
ansi_term = "0.12.1"
read-fonts = { path = "../read-fonts", features = ["test_data"]}
