[package]
name = "write-fonts"
version = "0.1.4"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Writing font files."
repository = "https://github.com/googlefonts/fontations"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
font-types = { version = "0.1.1", path = "../font-types" }
read-fonts = { version = "0.1.2", path = "../read-fonts" }
bitflags = "1.3"
kurbo = "0.9.1"

[dev-dependencies]
diff = "0.1.12"
ansi_term = "0.12.1"
read-fonts = { version = "0.1.2", path = "../read-fonts", features = ["test_data"] }
