[package]
name = "font-types"
version = "0.6.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Scalar types used in fonts."
repository = "https://github.com/googlefonts/fontations"
readme = "README.md"
categories = ["text-processing"]

[features]
std = []
bytemuck = ["dep:bytemuck"]
serde = ["dep:serde"]

[dependencies]
# note: bytemuck version must be available in all deployment environments
bytemuck = { workspace = true,  features = ["derive", "min_const_generics"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"
